[package]
name = "mbx-proc"
version = "0.1.0"
authors = ["Derpking"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full", "fold"] }